### ISSUE TITLE
italian char problem

### ISSUE THREAD

**Issue by intel2004** [MajicDesigns/MD_MAX72XX#6]
i try to modify the library to use some italian chars like 'è' or 'à' or 'ù'...
i found that in the library is already present in MD_MAX72xx_font.cpp
but apparently in the wrong place:
with serial bluetooth adapter i acqwuire the string to print on the display, but in corresponding of chars there is an error:
if i put 'è' i obtain '-¿', if i replace this on line 336:
5, 0x38, 0x54, 0x54, 0x55, 0x59,	// 168 - 'Inverted ?
with this (contasined in line 298):
  5, 0x38, 0x54, 0x54, 0x55, 0x59,	// 130 - 'e acute'
it's look like '-è'
there is another way to correct that?

**Comment by MajicDesigns** [comment]
You are entering characters a double byte characters rather than single byte ASCII characters.

The Parola library has and example UFT-8_Display that shows how UTF-8 multi-byte characters can be mapped to Extended ASCII characters that can be displayed with a suitable font file. This could be applied to the MD_MAX72XX library, but you will need to do that yourself.
